name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Replace placeholders with secrets
      run: |
        sed -i "s|{{API_URL}}|${{ secrets.API_URL }}|g" index.html

    - name: Copy html to EC2
      run: |
        scp -o StrictHostKeyChecking=no index.html ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu

    - name: Move html
      run: |
        sudo mv /home/ubuntu/index.html /var/www/html/index.html
